<?php

use Illuminate\Database\Seeder;
use App\Models\Country;

/**
 * Class CountryTableSeeder
 */
class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::truncate();
        Country::unguard();
        

        Country::create(['name' => 'Colombia', 'a2-iso' => 'CO', 'a3-un' => 'COL', 'id' => '170', 'dialing' => '57', 'continent_id' => 1,]);
        Country::create(['name' => 'Afghanistan', 'a2-iso' => 'AF', 'a3-un' => 'AFG', 'id' => '4', 'dialing' => '93', 'continent_id' => 3,]);
        Country::create(['name' => 'Albania', 'a2-iso' => 'AL', 'a3-un' => 'ALB', 'id' => '8', 'dialing' => '355', 'continent_id' => 4,]);
        Country::create(['name' => 'Algeria', 'a2-iso' => 'DZ', 'a3-un' => 'DZA', 'id' => '12', 'dialing' => '213', 'continent_id' => 2,]);
        Country::create(['name' => 'American Samoa', 'a2-iso' => 'AS', 'a3-un' => 'ASM', 'id' => '16', 'dialing' => '1-684', 'continent_id' => 5,]);
        Country::create(['name' => 'Andorra', 'a2-iso' => 'AD', 'a3-un' => 'AND', 'id' => '20', 'dialing' => '376', 'continent_id' => 4,]);
        Country::create(['name' => 'Angola', 'a2-iso' => 'AO', 'a3-un' => 'AGO', 'id' => '24', 'dialing' => '244', 'continent_id' => 2,]);
        Country::create(['name' => 'Anguilla', 'a2-iso' => 'AI', 'a3-un' => 'AIA', 'id' => '660', 'dialing' => '1-264', 'continent_id' => 1,]);
        Country::create(['name' => 'Antigua and Barbuda', 'a2-iso' => 'AG', 'a3-un' => 'ATG', 'id' => '28', 'dialing' => '1-268', 'continent_id' => 1,]);
        Country::create(['name' => 'Argentina', 'a2-iso' => 'AR', 'a3-un' => 'ARG', 'id' => '32', 'dialing' => '54', 'continent_id' => 1,]);
        Country::create(['name' => 'Armenia', 'a2-iso' => 'AM', 'a3-un' => 'ARM', 'id' => '51', 'dialing' => '374', 'continent_id' => 3,]);
        Country::create(['name' => 'Aruba', 'a2-iso' => 'AW', 'a3-un' => 'ABW', 'id' => '533', 'dialing' => '297', 'continent_id' => 1,]);
        Country::create(['name' => 'Australia', 'a2-iso' => 'AU', 'a3-un' => 'AUS', 'id' => '36', 'dialing' => '61', 'continent_id' => 5,]);
        Country::create(['name' => 'Austria', 'a2-iso' => 'AT', 'a3-un' => 'AUT', 'id' => '40', 'dialing' => '43', 'continent_id' => 4,]);
        Country::create(['name' => 'Azerbaijan', 'a2-iso' => 'AZ', 'a3-un' => 'AZE', 'id' => '31', 'dialing' => '994', 'continent_id' => 3,]);
        Country::create(['name' => 'Bahamas', 'a2-iso' => 'BS', 'a3-un' => 'BHS', 'id' => '44', 'dialing' => '1-242', 'continent_id' => 1,]);
        Country::create(['name' => 'Bahrain', 'a2-iso' => 'BH', 'a3-un' => 'BHR', 'id' => '48', 'dialing' => '973', 'continent_id' => 3,]);
        Country::create(['name' => 'Bangladesh', 'a2-iso' => 'BD', 'a3-un' => 'BGD', 'id' => '50', 'dialing' => '880', 'continent_id' => 3,]);
        Country::create(['name' => 'Barbados', 'a2-iso' => 'BB', 'a3-un' => 'BRB', 'id' => '52', 'dialing' => '1-246', 'continent_id' => 1,]);
        Country::create(['name' => 'Belarus', 'a2-iso' => 'BY', 'a3-un' => 'BLR', 'id' => '112', 'dialing' => '375', 'continent_id' => 3,]);
        Country::create(['name' => 'Belgium', 'a2-iso' => 'BE', 'a3-un' => 'BEL', 'id' => '56', 'dialing' => '32', 'continent_id' => 4,]);
        Country::create(['name' => 'Belize', 'a2-iso' => 'BZ', 'a3-un' => 'BLZ', 'id' => '84', 'dialing' => '501', 'continent_id' => 1,]);
        Country::create(['name' => 'Benin', 'a2-iso' => 'BJ', 'a3-un' => 'BEN', 'id' => '204', 'dialing' => '229', 'continent_id' => 2,]);
        Country::create(['name' => 'Bermuda', 'a2-iso' => 'BM', 'a3-un' => 'BMU', 'id' => '60', 'dialing' => '1-441', 'continent_id' => 1,]);
        Country::create(['name' => 'Bhutan', 'a2-iso' => 'BT', 'a3-un' => 'BTN', 'id' => '64', 'dialing' => '975', 'continent_id' => 3,]);
        Country::create(['name' => 'Bolivia', 'a2-iso' => 'BO', 'a3-un' => 'BOL', 'id' => '68', 'dialing' => '591', 'continent_id' => 1,]);
        Country::create(['name' => 'Bosnia and Herzegovina', 'a2-iso' => 'BA', 'a3-un' => 'BIH', 'id' => '70', 'dialing' => '387', 'continent_id' => 4,]);
        Country::create(['name' => 'Botswana', 'a2-iso' => 'BW', 'a3-un' => 'BWA', 'id' => '72', 'dialing' => '267', 'continent_id' => 2,]);
        Country::create(['name' => 'Brasil', 'a2-iso' => 'BR', 'a3-un' => 'BRA', 'id' => '76', 'dialing' => '55', 'continent_id' => 1,]);
        Country::create(['name' => 'British Indian Ocean Territory', 'a2-iso' => 'IO', 'a3-un' => 'IOT', 'id' => '86', 'dialing' => '246', 'continent_id' => 1,]);
        Country::create(['name' => 'Brunei Darussalam', 'a2-iso' => 'BN', 'a3-un' => 'BRN', 'id' => '96', 'dialing' => '673', 'continent_id' => 3,]);
        Country::create(['name' => 'Bulgaria', 'a2-iso' => 'BG', 'a3-un' => 'BGR', 'id' => '100', 'dialing' => '359', 'continent_id' => 4,]);
        Country::create(['name' => 'Burkina Faso', 'a2-iso' => 'BF', 'a3-un' => 'BFA', 'id' => '854', 'dialing' => '226', 'continent_id' => 2,]);
        Country::create(['name' => 'Burundi', 'a2-iso' => 'BI', 'a3-un' => 'BDI', 'id' => '108', 'dialing' => '257', 'continent_id' => 2,]);
        Country::create(['name' => 'Cambodia', 'a2-iso' => 'KH', 'a3-un' => 'KHM', 'id' => '116', 'dialing' => '855', 'continent_id' => 3,]);
        Country::create(['name' => 'Cameroon', 'a2-iso' => 'CM', 'a3-un' => 'CMR', 'id' => '120', 'dialing' => '237', 'continent_id' => 2,]);
        Country::create(['name' => 'Canada', 'a2-iso' => 'CA', 'a3-un' => 'CAN', 'id' => '124', 'dialing' => '1', 'continent_id' => 1,]);
        Country::create(['name' => 'Cape Verde', 'a2-iso' => 'CV', 'a3-un' => 'CPV', 'id' => '132', 'dialing' => '238', 'continent_id' => 2,]);
        Country::create(['name' => 'Cayman Islands', 'a2-iso' => 'KY', 'a3-un' => 'CYM', 'id' => '136', 'dialing' => '1-345', 'continent_id' => 1,]);
        Country::create(['name' => 'Central African Republic', 'a2-iso' => 'CF', 'a3-un' => 'CAF', 'id' => '140', 'dialing' => '236', 'continent_id' => 2,]);
        Country::create(['name' => 'Chad', 'a2-iso' => 'TD', 'a3-un' => 'TCD', 'id' => '148', 'dialing' => '235', 'continent_id' => 2,]);
        Country::create(['name' => 'Chile', 'a2-iso' => 'CL', 'a3-un' => 'CHL', 'id' => '152', 'dialing' => '56', 'continent_id' => 1,]);
        Country::create(['name' => 'China', 'a2-iso' => 'CN', 'a3-un' => 'CHN', 'id' => '156', 'dialing' => '86', 'continent_id' => 3,]);
        Country::create(['name' => 'Comoros', 'a2-iso' => 'KM', 'a3-un' => 'COM', 'id' => '174', 'dialing' => '269', 'continent_id' => 2,]);
        Country::create(['name' => 'Congo', 'a2-iso' => 'CG', 'a3-un' => 'COG', 'id' => '178', 'dialing' => '242', 'continent_id' => 2,]);
        Country::create(['name' => 'Democratic Republic of the Congo', 'a2-iso' => 'CD', 'a3-un' => 'COD', 'id' => '180', 'dialing' => '243', 'continent_id' => 2,]);
        Country::create(['name' => 'Cook Islands', 'a2-iso' => 'CK', 'a3-un' => 'COK', 'id' => '184', 'dialing' => '682', 'continent_id' => 5,]);
        Country::create(['name' => 'Costa Rica', 'a2-iso' => 'CR', 'a3-un' => 'CRI', 'id' => '188', 'dialing' => '506', 'continent_id' => 1,]);
        Country::create(['name' => 'Croatia', 'a2-iso' => 'HR', 'a3-un' => 'HRV', 'id' => '191', 'dialing' => '385', 'continent_id' => 4,]);
        Country::create(['name' => 'Cuba', 'a2-iso' => 'CU', 'a3-un' => 'CUB', 'id' => '192', 'dialing' => '53', 'continent_id' => 1,]);
        Country::create(['name' => 'Cyprus', 'a2-iso' => 'CY', 'a3-un' => 'CYP', 'id' => '196', 'dialing' => '357', 'continent_id' => 3,]);
        Country::create(['name' => 'Czech Republic', 'a2-iso' => 'CZ', 'a3-un' => 'CZE', 'id' => '203', 'dialing' => '420', 'continent_id' => 4,]);
        Country::create(['name' => 'Denmark', 'a2-iso' => 'DK', 'a3-un' => 'DNK', 'id' => '208', 'dialing' => '45', 'continent_id' => 4,]);
        Country::create(['name' => 'Djibouti', 'a2-iso' => 'DJ', 'a3-un' => 'DJI', 'id' => '262', 'dialing' => '253', 'continent_id' => 2,]);
        Country::create(['name' => 'Dominica', 'a2-iso' => 'DM', 'a3-un' => 'DMA', 'id' => '212', 'dialing' => '1-767', 'continent_id' => 1,]);
        Country::create(['name' => 'Dominican Republic', 'a2-iso' => 'DO', 'a3-un' => 'DOM', 'id' => '214', 'dialing' => '1-809,1-829,1-849', 'continent_id' => 1,]);
        Country::create(['name' => 'Ecuador', 'a2-iso' => 'EC', 'a3-un' => 'ECU', 'id' => '218', 'dialing' => '593', 'continent_id' => 1,]);
        Country::create(['name' => 'Egypt', 'a2-iso' => 'EG', 'a3-un' => 'EGY', 'id' => '818', 'dialing' => '20', 'continent_id' => 2,]);
        Country::create(['name' => 'El Salvador', 'a2-iso' => 'SV', 'a3-un' => 'SLV', 'id' => '222', 'dialing' => '503', 'continent_id' => 1,]);
        Country::create(['name' => 'Equatorial Guinea', 'a2-iso' => 'GQ', 'a3-un' => 'GNQ', 'id' => '226', 'dialing' => '240', 'continent_id' => 2,]);
        Country::create(['name' => 'Eritrea', 'a2-iso' => 'ER', 'a3-un' => 'ERI', 'id' => '232', 'dialing' => '291', 'continent_id' => 2,]);
        Country::create(['name' => 'Estonia', 'a2-iso' => 'EE', 'a3-un' => 'EST', 'id' => '233', 'dialing' => '372', 'continent_id' => 4,]);
        Country::create(['name' => 'Ethiopia', 'a2-iso' => 'ET', 'a3-un' => 'ETH', 'id' => '231', 'dialing' => '251', 'continent_id' => 2,]);
        Country::create(['name' => 'Faroe Islands', 'a2-iso' => 'FO', 'a3-un' => 'FRO', 'id' => '234', 'dialing' => '298', 'continent_id' => 4,]);
        Country::create(['name' => 'Fiji', 'a2-iso' => 'FJ', 'a3-un' => 'FJI', 'id' => '242', 'dialing' => '679', 'continent_id' => 5,]);
        Country::create(['name' => 'Finland', 'a2-iso' => 'FI', 'a3-un' => 'FIN', 'id' => '246', 'dialing' => '358', 'continent_id' => 4,]);
        Country::create(['name' => 'France', 'a2-iso' => 'FR', 'a3-un' => 'FRA', 'id' => '250', 'dialing' => '33', 'continent_id' => 4,]);
        Country::create(['name' => 'French Guiana', 'a2-iso' => 'GF', 'a3-un' => 'GUF', 'id' => '254', 'dialing' => '594', 'continent_id' => 1,]);
        Country::create(['name' => 'French Polynesia', 'a2-iso' => 'PF', 'a3-un' => 'PYF', 'id' => '258', 'dialing' => '689', 'continent_id' => 5,]);
        Country::create(['name' => 'Gabon', 'a2-iso' => 'GA', 'a3-un' => 'GAB', 'id' => '266', 'dialing' => '241', 'continent_id' => 2,]);
        Country::create(['name' => 'Gambia', 'a2-iso' => 'GM', 'a3-un' => 'GMB', 'id' => '270', 'dialing' => '220', 'continent_id' => 2,]);
        Country::create(['name' => 'Georgia', 'a2-iso' => 'GE', 'a3-un' => 'GEO', 'id' => '268', 'dialing' => '995', 'continent_id' => 3,]);
        Country::create(['name' => 'Germany', 'a2-iso' => 'DE', 'a3-un' => 'DEU', 'id' => '276', 'dialing' => '49', 'continent_id' => 4,]);
        Country::create(['name' => 'Ghana', 'a2-iso' => 'GH', 'a3-un' => 'GHA', 'id' => '288', 'dialing' => '233', 'continent_id' => 2,]);
        Country::create(['name' => 'Gibraltar', 'a2-iso' => 'GI', 'a3-un' => 'GIB', 'id' => '292', 'dialing' => '350', 'continent_id' => 4,]);
        Country::create(['name' => 'Greece', 'a2-iso' => 'GR', 'a3-un' => 'GRC', 'id' => '300', 'dialing' => '30', 'continent_id' => 4,]);
        Country::create(['name' => 'Greenland', 'a2-iso' => 'GL', 'a3-un' => 'GRL', 'id' => '304', 'dialing' => '299', 'continent_id' => 1,]);
        Country::create(['name' => 'Grenada', 'a2-iso' => 'GD', 'a3-un' => 'GRD', 'id' => '308', 'dialing' => '1-473', 'continent_id' => 1,]);
        Country::create(['name' => 'Guadeloupe', 'a2-iso' => 'GP', 'a3-un' => 'GLP', 'id' => '312', 'dialing' => '590', 'continent_id' => 1,]);
        Country::create(['name' => 'Guam', 'a2-iso' => 'GU', 'a3-un' => 'GUM', 'id' => '316', 'dialing' => '1-671', 'continent_id' => 5,]);
        Country::create(['name' => 'Guatemala', 'a2-iso' => 'GT', 'a3-un' => 'GTM', 'id' => '320', 'dialing' => '502', 'continent_id' => 1,]);
        Country::create(['name' => 'Guernsey', 'a2-iso' => 'GG', 'a3-un' => 'GGY', 'id' => '831', 'dialing' => '44', 'continent_id' => 4,]);
        Country::create(['name' => 'Guinea', 'a2-iso' => 'GN', 'a3-un' => 'GIN', 'id' => '324', 'dialing' => '224', 'continent_id' => 2,]);
        Country::create(['name' => 'Guinea-Bissau', 'a2-iso' => 'GW', 'a3-un' => 'GNB', 'id' => '624', 'dialing' => '245', 'continent_id' => 2,]);
        Country::create(['name' => 'Guyana', 'a2-iso' => 'GY', 'a3-un' => 'GUY', 'id' => '328', 'dialing' => '592', 'continent_id' => 1,]);
        Country::create(['name' => 'Haiti', 'a2-iso' => 'HT', 'a3-un' => 'HTI', 'id' => '332', 'dialing' => '509', 'continent_id' => 1,]);
        Country::create(['name' => 'Honduras', 'a2-iso' => 'HN', 'a3-un' => 'HND', 'id' => '340', 'dialing' => '504', 'continent_id' => 1,]);
        Country::create(['name' => 'Hong Kong', 'a2-iso' => 'HK', 'a3-un' => 'HKG', 'id' => '344', 'dialing' => '852', 'continent_id' => 3,]);
        Country::create(['name' => 'Hungary', 'a2-iso' => 'HU', 'a3-un' => 'HUN', 'id' => '348', 'dialing' => '36', 'continent_id' => 4,]);
        Country::create(['name' => 'Iceland', 'a2-iso' => 'IS', 'a3-un' => 'ISL', 'id' => '352', 'dialing' => '354', 'continent_id' => 4,]);
        Country::create(['name' => 'India', 'a2-iso' => 'IN', 'a3-un' => 'IND', 'id' => '356', 'dialing' => '91', 'continent_id' => 3,]);
        Country::create(['name' => 'Indonesia', 'a2-iso' => 'ID', 'a3-un' => 'IDN', 'id' => '360', 'dialing' => '62', 'continent_id' => 3,]);
        Country::create(['name' => 'Iran, Islamic Republic of', 'a2-iso' => 'IR', 'a3-un' => 'IRN', 'id' => '364', 'dialing' => '98', 'continent_id' => 3,]);
        Country::create(['name' => 'Iraq', 'a2-iso' => 'IQ', 'a3-un' => 'IRQ', 'id' => '368', 'dialing' => '964', 'continent_id' => 3,]);
        Country::create(['name' => 'Ireland', 'a2-iso' => 'IE', 'a3-un' => 'IRL', 'id' => '372', 'dialing' => '353', 'continent_id' => 4,]);
        Country::create(['name' => 'Isle of Man', 'a2-iso' => 'IM', 'a3-un' => 'IMN', 'id' => '833', 'dialing' => '', 'continent_id' => 4,]);
        Country::create(['name' => 'Israel', 'a2-iso' => 'IL', 'a3-un' => 'ISR', 'id' => '376', 'dialing' => '972', 'continent_id' => 3,]);
        Country::create(['name' => 'Italy', 'a2-iso' => 'IT', 'a3-un' => 'ITA', 'id' => '380', 'dialing' => '39', 'continent_id' => 4,]);
        Country::create(['name' => 'Jamaica', 'a2-iso' => 'JM', 'a3-un' => 'JAM', 'id' => '388', 'dialing' => '1-876', 'continent_id' => 1,]);
        Country::create(['name' => 'Japan', 'a2-iso' => 'JP', 'a3-un' => 'JPN', 'id' => '392', 'dialing' => '81', 'continent_id' => 3,]);
        Country::create(['name' => 'Jersey', 'a2-iso' => 'JE', 'a3-un' => 'JEY', 'id' => '832', 'dialing' => '44', 'continent_id' => 4,]);
        Country::create(['name' => 'Jordan', 'a2-iso' => 'JO', 'a3-un' => 'JOR', 'id' => '400', 'dialing' => '962', 'continent_id' => 3,]);
        Country::create(['name' => 'Kazakhstan', 'a2-iso' => 'KZ', 'a3-un' => 'KAZ', 'id' => '398', 'dialing' => '7', 'continent_id' => 3,]);
        Country::create(['name' => 'Kenya', 'a2-iso' => 'KE', 'a3-un' => 'KEN', 'id' => '404', 'dialing' => '254', 'continent_id' => 2,]);
        Country::create(['name' => 'Kiribati', 'a2-iso' => 'KI', 'a3-un' => 'KIR', 'id' => '296', 'dialing' => '686', 'continent_id' => 5,]);
        Country::create(['name' => 'Korea, Democratic Peoples Republic of', 'a2-iso' => 'KP', 'a3-un' => 'PRK', 'id' => '408', 'dialing' => '850', 'continent_id' => 3,]);
        Country::create(['name' => 'Korea, Republic of', 'a2-iso' => 'KR', 'a3-un' => 'KOR', 'id' => '410', 'dialing' => '82', 'continent_id' => 3,]);
        Country::create(['name' => 'Kuwait', 'a2-iso' => 'KW', 'a3-un' => 'KWT', 'id' => '414', 'dialing' => '965', 'continent_id' => 3,]);
        Country::create(['name' => 'Kyrgyzstan', 'a2-iso' => 'KG', 'a3-un' => 'KGZ', 'id' => '417', 'dialing' => '996', 'continent_id' => 3,]);
        Country::create(['name' => 'Lao Peoples Democratic Republic', 'a2-iso' => 'LA', 'a3-un' => 'LAO', 'id' => '418', 'dialing' => '856', 'continent_id' => 3,]);
        Country::create(['name' => 'Latvia', 'a2-iso' => 'LV', 'a3-un' => 'LVA', 'id' => '428', 'dialing' => '371', 'continent_id' => 4,]);
        Country::create(['name' => 'Lebanon', 'a2-iso' => 'LB', 'a3-un' => 'LBN', 'id' => '422', 'dialing' => '961', 'continent_id' => 3,]);
        Country::create(['name' => 'Lesotho', 'a2-iso' => 'LS', 'a3-un' => 'LSO', 'id' => '426', 'dialing' => '266', 'continent_id' => 2,]);
        Country::create(['name' => 'Liberia', 'a2-iso' => 'LR', 'a3-un' => 'LBR', 'id' => '430', 'dialing' => '231', 'continent_id' => 2,]);
        Country::create(['name' => 'Libya', 'a2-iso' => 'LY', 'a3-un' => 'LBY', 'id' => '434', 'dialing' => '218', 'continent_id' => 2,]);
        Country::create(['name' => 'Liechtenstein', 'a2-iso' => 'LI', 'a3-un' => 'LIE', 'id' => '438', 'dialing' => '423', 'continent_id' => 4,]);
        Country::create(['name' => 'Lithuania', 'a2-iso' => 'LT', 'a3-un' => 'LTU', 'id' => '440', 'dialing' => '370', 'continent_id' => 4,]);
        Country::create(['name' => 'Luxembourg', 'a2-iso' => 'LU', 'a3-un' => 'LUX', 'id' => '442', 'dialing' => '352', 'continent_id' => 4,]);
        Country::create(['name' => 'Macao', 'a2-iso' => 'MO', 'a3-un' => 'MAC', 'id' => '446', 'dialing' => '853', 'continent_id' => 3,]);
        Country::create(['name' => 'Macedonia, the Former Yugoslav Republic of', 'a2-iso' => 'MK', 'a3-un' => 'MKD', 'id' => '807', 'dialing' => '389', 'continent_id' => 4,]);
        Country::create(['name' => 'Madagascar', 'a2-iso' => 'MG', 'a3-un' => 'MDG', 'id' => '450', 'dialing' => '261', 'continent_id' => 2,]);
        Country::create(['name' => 'Malawi', 'a2-iso' => 'MW', 'a3-un' => 'MWI', 'id' => '454', 'dialing' => '265', 'continent_id' => 2,]);
        Country::create(['name' => 'Malaysia', 'a2-iso' => 'MY', 'a3-un' => 'MYS', 'id' => '458', 'dialing' => '60', 'continent_id' => 3,]);
        Country::create(['name' => 'Maldives', 'a2-iso' => 'MV', 'a3-un' => 'MDV', 'id' => '462', 'dialing' => '960', 'continent_id' => 3,]);
        Country::create(['name' => 'Mali', 'a2-iso' => 'ML', 'a3-un' => 'MLI', 'id' => '466', 'dialing' => '223', 'continent_id' => 2,]);
        Country::create(['name' => 'Malta', 'a2-iso' => 'MT', 'a3-un' => 'MLT', 'id' => '470', 'dialing' => '356', 'continent_id' => 4,]);
        Country::create(['name' => 'Marshall Islands', 'a2-iso' => 'MH', 'a3-un' => 'MHL', 'id' => '584', 'dialing' => '692', 'continent_id' => 5,]);
        Country::create(['name' => 'Martinique', 'a2-iso' => 'MQ', 'a3-un' => 'MTQ', 'id' => '474', 'dialing' => '596', 'continent_id' => 1,]);
        Country::create(['name' => 'Mauritania', 'a2-iso' => 'MR', 'a3-un' => 'MRT', 'id' => '478', 'dialing' => '222', 'continent_id' => 2,]);
        Country::create(['name' => 'Mauritius', 'a2-iso' => 'MU', 'a3-un' => 'MUS', 'id' => '480', 'dialing' => '230', 'continent_id' => 2,]);
        Country::create(['name' => 'Mayotte', 'a2-iso' => 'YT', 'a3-un' => 'MYT', 'id' => '175', 'dialing' => '262', 'continent_id' => 2,]);
        Country::create(['name' => 'Mexico', 'a2-iso' => 'MX', 'a3-un' => 'MEX', 'id' => '484', 'dialing' => '52', 'continent_id' => 1,]);
        Country::create(['name' => 'Micronesia, Federated States of', 'a2-iso' => 'FM', 'a3-un' => 'FSM', 'id' => '583', 'dialing' => '691', 'continent_id' => 5,]);
        Country::create(['name' => 'Moldova, Republic of', 'a2-iso' => 'MD', 'a3-un' => 'MDA', 'id' => '498', 'dialing' => '373', 'continent_id' => 3,]);
        Country::create(['name' => 'Monaco', 'a2-iso' => 'MC', 'a3-un' => 'MCO', 'id' => '492', 'dialing' => '377', 'continent_id' => 4,]);
        Country::create(['name' => 'Mongolia', 'a2-iso' => 'MN', 'a3-un' => 'MNG', 'id' => '496', 'dialing' => '976', 'continent_id' => 3,]);
        Country::create(['name' => 'Montserrat', 'a2-iso' => 'MS', 'a3-un' => 'MSR', 'id' => '500', 'dialing' => '1-664', 'continent_id' => 1,]);
        Country::create(['name' => 'Morocco', 'a2-iso' => 'MA', 'a3-un' => 'MAR', 'id' => '504', 'dialing' => '212', 'continent_id' => 2,]);
        Country::create(['name' => 'Mozambique', 'a2-iso' => 'MZ', 'a3-un' => 'MOZ', 'id' => '508', 'dialing' => '258', 'continent_id' => 2,]);
        Country::create(['name' => 'Namibia', 'a2-iso' => 'NA', 'a3-un' => 'NAM', 'id' => '516', 'dialing' => '264', 'continent_id' => 2,]);
        Country::create(['name' => 'Nauru', 'a2-iso' => 'NR', 'a3-un' => 'NRU', 'id' => '520', 'dialing' => '674', 'continent_id' => 5,]);
        Country::create(['name' => 'Nepal', 'a2-iso' => 'NP', 'a3-un' => 'NPL', 'id' => '524', 'dialing' => '977', 'continent_id' => 3,]);
        Country::create(['name' => 'Netherlands', 'a2-iso' => 'NL', 'a3-un' => 'NLD', 'id' => '528', 'dialing' => '31', 'continent_id' => 4,]);
        Country::create(['name' => 'New Caledonia', 'a2-iso' => 'NC', 'a3-un' => 'NCL', 'id' => '540', 'dialing' => '687', 'continent_id' => 5,]);
        Country::create(['name' => 'New Zealand', 'a2-iso' => 'NZ', 'a3-un' => 'NZL', 'id' => '554', 'dialing' => '64', 'continent_id' => 5,]);
        Country::create(['name' => 'Nicaragua', 'a2-iso' => 'NI', 'a3-un' => 'NIC', 'id' => '558', 'dialing' => '505', 'continent_id' => 1,]);
        Country::create(['name' => 'Niger', 'a2-iso' => 'NE', 'a3-un' => 'NER', 'id' => '562', 'dialing' => '227', 'continent_id' => 2,]);
        Country::create(['name' => 'Nigeria', 'a2-iso' => 'NG', 'a3-un' => 'NGA', 'id' => '566', 'dialing' => '234', 'continent_id' => 2,]);
        Country::create(['name' => 'Northern Mariana Islands', 'a2-iso' => 'MP', 'a3-un' => 'MNP', 'id' => '580', 'dialing' => '1-670', 'continent_id' => 5,]);
        Country::create(['name' => 'Norway', 'a2-iso' => 'NO', 'a3-un' => 'NOR', 'id' => '578', 'dialing' => '47', 'continent_id' => 4,]);
        Country::create(['name' => 'Oman', 'a2-iso' => 'OM', 'a3-un' => 'OMN', 'id' => '512', 'dialing' => '968', 'continent_id' => 3,]);
        Country::create(['name' => 'Pakistan', 'a2-iso' => 'PK', 'a3-un' => 'PAK', 'id' => '586', 'dialing' => '92', 'continent_id' => 3,]);
        Country::create(['name' => 'Palau', 'a2-iso' => 'PW', 'a3-un' => 'PLW', 'id' => '585', 'dialing' => '680', 'continent_id' => 5,]);
        Country::create(['name' => 'Panama', 'a2-iso' => 'PA', 'a3-un' => 'PAN', 'id' => '591', 'dialing' => '507', 'continent_id' => 1,]);
        Country::create(['name' => 'Papua New Guinea', 'a2-iso' => 'PG', 'a3-un' => 'PNG', 'id' => '598', 'dialing' => '675', 'continent_id' => 5,]);
        Country::create(['name' => 'Paraguay', 'a2-iso' => 'PY', 'a3-un' => 'PRY', 'id' => '600', 'dialing' => '595', 'continent_id' => 1,]);
        Country::create(['name' => 'Peru', 'a2-iso' => 'PE', 'a3-un' => 'PER', 'id' => '604', 'dialing' => '51', 'continent_id' => 1,]);
        Country::create(['name' => 'Philippines', 'a2-iso' => 'PH', 'a3-un' => 'PHL', 'id' => '608', 'dialing' => '63', 'continent_id' => 3,]);
        Country::create(['name' => 'Poland', 'a2-iso' => 'PL', 'a3-un' => 'POL', 'id' => '616', 'dialing' => '48', 'continent_id' => 4,]);
        Country::create(['name' => 'Portugal', 'a2-iso' => 'PT', 'a3-un' => 'PRT', 'id' => '620', 'dialing' => '351', 'continent_id' => 4,]);
        Country::create(['name' => 'Puerto Rico', 'a2-iso' => 'PR', 'a3-un' => 'PRI', 'id' => '630', 'dialing' => '1', 'continent_id' => 1,]);
        Country::create(['name' => 'Qatar', 'a2-iso' => 'QA', 'a3-un' => 'QAT', 'id' => '634', 'dialing' => '974', 'continent_id' => 3,]);
        Country::create(['name' => 'Romania', 'a2-iso' => 'RO', 'a3-un' => 'ROU', 'id' => '642', 'dialing' => '40', 'continent_id' => 4,]);
        Country::create(['name' => 'Russian Federation', 'a2-iso' => 'RU', 'a3-un' => 'RUS', 'id' => '643', 'dialing' => '7', 'continent_id' => 3,]);
        Country::create(['name' => 'Rwanda', 'a2-iso' => 'RW', 'a3-un' => 'RWA', 'id' => '646', 'dialing' => '250', 'continent_id' => 2,]);
        Country::create(['name' => 'Saint Helena', 'a2-iso' => 'SH', 'a3-un' => 'SHN', 'id' => '654', 'dialing' => '290', 'continent_id' => 2,]);
        Country::create(['name' => 'Saint Kitts and Nevis', 'a2-iso' => 'KN', 'a3-un' => 'KNA', 'id' => '659', 'dialing' => '1-869', 'continent_id' => 1,]);
        Country::create(['name' => 'Saint Lucia', 'a2-iso' => 'LC', 'a3-un' => 'LCA', 'id' => '662', 'dialing' => '1-758', 'continent_id' => 1,]);
        Country::create(['name' => 'Saint Pierre and Miquelon', 'a2-iso' => 'PM', 'a3-un' => 'SPM', 'id' => '666', 'dialing' => '508', 'continent_id' => 1,]);
        Country::create(['name' => 'Saint Vincent and the Grenadines', 'a2-iso' => 'VC', 'a3-un' => 'VCT', 'id' => '670', 'dialing' => '1-784', 'continent_id' => 1,]);
        Country::create(['name' => 'Samoa', 'a2-iso' => 'WS', 'a3-un' => 'WSM', 'id' => '882', 'dialing' => '685', 'continent_id' => 5,]);
        Country::create(['name' => 'San Marino', 'a2-iso' => 'SM', 'a3-un' => 'SMR', 'id' => '674', 'dialing' => '378', 'continent_id' => 4,]);
        Country::create(['name' => 'Sao Tome and Principe', 'a2-iso' => 'ST', 'a3-un' => 'STP', 'id' => '678', 'dialing' => '239', 'continent_id' => 2,]);
        Country::create(['name' => 'Saudi Arabia', 'a2-iso' => 'SA', 'a3-un' => 'SAU', 'id' => '682', 'dialing' => '966', 'continent_id' => 3,]);
        Country::create(['name' => 'Senegal', 'a2-iso' => 'SN', 'a3-un' => 'SEN', 'id' => '686', 'dialing' => '221', 'continent_id' => 2,]);
        Country::create(['name' => 'Serbia', 'a2-iso' => 'RS', 'a3-un' => 'SRB', 'id' => '688', 'dialing' => '381', 'continent_id' => 4,]);
        Country::create(['name' => 'Seychelles', 'a2-iso' => 'SC', 'a3-un' => 'SYC', 'id' => '690', 'dialing' => '248', 'continent_id' => 2,]);
        Country::create(['name' => 'Sierra Leone', 'a2-iso' => 'SL', 'a3-un' => 'SLE', 'id' => '694', 'dialing' => '232', 'continent_id' => 2,]);
        Country::create(['name' => 'Singapore', 'a2-iso' => 'SG', 'a3-un' => 'SGP', 'id' => '702', 'dialing' => '65', 'continent_id' => 3,]);
        Country::create(['name' => 'Slovakia', 'a2-iso' => 'SK', 'a3-un' => 'SVK', 'id' => '703', 'dialing' => '421', 'continent_id' => 4,]);
        Country::create(['name' => 'Slovenia', 'a2-iso' => 'SI', 'a3-un' => 'SVN', 'id' => '705', 'dialing' => '386', 'continent_id' => 4,]);
        Country::create(['name' => 'Solomon Islands', 'a2-iso' => 'SB', 'a3-un' => 'SLB', 'id' => '90', 'dialing' => '677', 'continent_id' => 5,]);
        Country::create(['name' => 'Somalia', 'a2-iso' => 'SO', 'a3-un' => 'SOM', 'id' => '706', 'dialing' => '252', 'continent_id' => 2,]);
        Country::create(['name' => 'South Africa', 'a2-iso' => 'ZA', 'a3-un' => 'ZAF', 'id' => '710', 'dialing' => '27', 'continent_id' => 2,]);
        Country::create(['name' => 'Spain', 'a2-iso' => 'ES', 'a3-un' => 'ESP', 'id' => '724', 'dialing' => '34', 'continent_id' => 4,]);
        Country::create(['name' => 'Sri Lanka', 'a2-iso' => 'LK', 'a3-un' => 'LKA', 'id' => '144', 'dialing' => '94', 'continent_id' => 3,]);
        Country::create(['name' => 'Sudan', 'a2-iso' => 'SD', 'a3-un' => 'SDN', 'id' => '729', 'dialing' => '249', 'continent_id' => 2,]);
        Country::create(['name' => 'Suriname', 'a2-iso' => 'SR', 'a3-un' => 'SUR', 'id' => '740', 'dialing' => '597', 'continent_id' => 1,]);
        Country::create(['name' => 'Swaziland', 'a2-iso' => 'SZ', 'a3-un' => 'SWZ', 'id' => '748', 'dialing' => '268', 'continent_id' => 2,]);
        Country::create(['name' => 'Sweden', 'a2-iso' => 'SE', 'a3-un' => 'SWE', 'id' => '752', 'dialing' => '46', 'continent_id' => 4,]);
        Country::create(['name' => 'Switzerland', 'a2-iso' => 'CH', 'a3-un' => 'CHE', 'id' => '756', 'dialing' => '41', 'continent_id' => 4,]);
        Country::create(['name' => 'Syrian Arab Republic', 'a2-iso' => 'SY', 'a3-un' => 'SYR', 'id' => '760', 'dialing' => '963', 'continent_id' => 3,]);
        Country::create(['name' => 'Taiwan', 'a2-iso' => 'TW', 'a3-un' => 'TWN', 'id' => '158', 'dialing' => '886', 'continent_id' => 3,]);
        Country::create(['name' => 'Tajikistan', 'a2-iso' => 'TJ', 'a3-un' => 'TJK', 'id' => '762', 'dialing' => '992', 'continent_id' => 3,]);
        Country::create(['name' => 'United Republic of Tanzania', 'a2-iso' => 'TZ', 'a3-un' => 'TZA', 'id' => '834', 'dialing' => '255', 'continent_id' => 2,]);
        Country::create(['name' => 'Thailand', 'a2-iso' => 'TH', 'a3-un' => 'THA', 'id' => '764', 'dialing' => '66', 'continent_id' => 3,]);
        Country::create(['name' => 'Togo', 'a2-iso' => 'TG', 'a3-un' => 'TGO', 'id' => '768', 'dialing' => '228', 'continent_id' => 2,]);
        Country::create(['name' => 'Tonga', 'a2-iso' => 'TO', 'a3-un' => 'TON', 'id' => '776', 'dialing' => '676', 'continent_id' => 5,]);
        Country::create(['name' => 'Trinidad and Tobago', 'a2-iso' => 'TT', 'a3-un' => 'TTO', 'id' => '780', 'dialing' => '1-868', 'continent_id' => 1,]);
        Country::create(['name' => 'Tunisia', 'a2-iso' => 'TN', 'a3-un' => 'TUN', 'id' => '788', 'dialing' => '216', 'continent_id' => 2,]);
        Country::create(['name' => 'Turkey', 'a2-iso' => 'TR', 'a3-un' => 'TUR', 'id' => '792', 'dialing' => '90', 'continent_id' => 3,]);
        Country::create(['name' => 'Turkmenistan', 'a2-iso' => 'TM', 'a3-un' => 'TKM', 'id' => '795', 'dialing' => '993', 'continent_id' => 3,]);
        Country::create(['name' => 'Turks and Caicos Islands', 'a2-iso' => 'TC', 'a3-un' => 'TCA', 'id' => '796', 'dialing' => '1-649', 'continent_id' => 1,]);
        Country::create(['name' => 'Tuvalu', 'a2-iso' => 'TV', 'a3-un' => 'TUV', 'id' => '798', 'dialing' => '688', 'continent_id' => 5,]);
        Country::create(['name' => 'Uganda', 'a2-iso' => 'UG', 'a3-un' => 'UGA', 'id' => '800', 'dialing' => '256', 'continent_id' => 2,]);
        Country::create(['name' => 'Ukraine', 'a2-iso' => 'UA', 'a3-un' => 'UKR', 'id' => '804', 'dialing' => '380', 'continent_id' => 3,]);
        Country::create(['name' => 'United Arab Emirates', 'a2-iso' => 'AE', 'a3-un' => 'ARE', 'id' => '784', 'dialing' => '971', 'continent_id' => 3,]);
        Country::create(['name' => 'United Kingdom', 'a2-iso' => 'GB', 'a3-un' => 'GBR', 'id' => '826', 'dialing' => '44', 'continent_id' => 4,]);
        Country::create(['name' => 'United States', 'a2-iso' => 'US', 'a3-un' => 'USA', 'id' => '840', 'dialing' => '1', 'continent_id' => 1,]);
        Country::create(['name' => 'Uruguay', 'a2-iso' => 'UY', 'a3-un' => 'URY', 'id' => '858', 'dialing' => '598', 'continent_id' => 1,]);
        Country::create(['name' => 'Uzbekistan', 'a2-iso' => 'UZ', 'a3-un' => 'UZB', 'id' => '860', 'dialing' => '998', 'continent_id' => 3,]);
        Country::create(['name' => 'Vanuatu', 'a2-iso' => 'VU', 'a3-un' => 'VUT', 'id' => '548', 'dialing' => '678', 'continent_id' => 5,]);
        Country::create(['name' => 'Venezuela', 'a2-iso' => 'VE', 'a3-un' => 'VEN', 'id' => '862', 'dialing' => '58', 'continent_id' => 1,]);
        Country::create(['name' => 'Viet Nam', 'a2-iso' => 'VN', 'a3-un' => 'VNM', 'id' => '704', 'dialing' => '84', 'continent_id' => 3,]);
        Country::create(['name' => 'British Virgin Islands', 'a2-iso' => 'VG', 'a3-un' => 'VGB', 'id' => '92', 'dialing' => '1-284', 'continent_id' => 1,]);
        Country::create(['name' => 'Wallis and Futuna', 'a2-iso' => 'WF', 'a3-un' => 'WLF', 'id' => '876', 'dialing' => '681', 'continent_id' => 5,]);
        Country::create(['name' => 'Western Sahara', 'a2-iso' => 'EH', 'a3-un' => 'ESH', 'id' => '732', 'dialing' => '212', 'continent_id' => 2,]);
        Country::create(['name' => 'Yemen', 'a2-iso' => 'YE', 'a3-un' => 'YEM', 'id' => '887', 'dialing' => '967', 'continent_id' => 3,]);
        Country::create(['name' => 'Zambia', 'a2-iso' => 'ZM', 'a3-un' => 'ZMB', 'id' => '894', 'dialing' => '260', 'continent_id' => 2,]);
        Country::create(['name' => 'Zimbabwe', 'a2-iso' => 'ZW', 'a3-un' => 'ZWE', 'id' => '716', 'dialing' => '263', 'continent_id' => 2,]);

    }
}
